//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikkanwelzijn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clienten()
        {
            this.activiteiten = new HashSet<activiteiten>();
        }
        public clienten(string _clientvoornaam, string _clientachternaam, string _clienttussenvoegsel, string _clientadres, string _clientwoonplaats)
        {
            this.clientvoornaam = _clientvoornaam;
            this.clientachternaam = _clientachternaam;
            this.clienttussenvoegsel = _clienttussenvoegsel;
            this.clientadres = _clientadres;
            this.clientwoonplaats = _clientwoonplaats;
        }    
        public string clientvoornaam { get; set; }
        public string clientachternaam { get; set; }
        public string clienttussenvoegsel { get; set; }
        public int clientid { get; set; }
        public string clientadres { get; set; }
        public string clientwoonplaats { get; set; }
        public Nullable<int> organisatie_organisatieid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activiteiten> activiteiten { get; set; }
        public virtual organisatie organisatie { get; set; }
        public virtual voorkeuren voorkeuren { get; set; }
    }
}
