//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikkanwelzijn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clienten()
        {
            this.activiteiten = new HashSet<activiteiten>();
        }
    
        public int clientid { get; set; }
        public string clientnaam { get; set; }
        public string clientachternaam { get; set; }
        public string clienttussenvoegsel { get; set; }
        public string clientwoonplaats { get; set; }
        public string clientadres { get; set; }
        public string clientgeslacht { get; set; }
        public int organisatie_organisatieid { get; set; }
        public string voorkeur1 { get; set; }
        public string voorkeur2 { get; set; }
        public string voorkeur3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activiteiten> activiteiten { get; set; }
        public virtual organisatie organisatie { get; set; }
    }
}
