//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ikkanwelzijn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voorkeuren
    {
        public string voorkeur1 { get; set; }
        public string voorkeur2 { get; set; }
        public string voorkeur3 { get; set; }
        public Nullable<int> clientid { get; set; }
        public int clienten_clientid { get; set; }
    
        public virtual clienten clienten { get; set; }
    }
}
